{% set version = "79" %}

package:
  name: cromwell
  version: {{ version }}

source:
  - url: https://github.com/broadinstitute/cromwell/releases/download/{{ version }}/cromwell-{{ version }}.jar
    sha256: 251440bc78390f575e6a7145e038e386b6393a596db45a25888a3ba467879bce
    folder: cromwell
  - url: https://github.com/broadinstitute/cromwell/releases/download/{{ version }}/womtool-{{ version }}.jar
    sha256: 7804aecae96907bfdbcfd9b5fae31845947b3dbe976cb4529ad7f5e162221537
    folder: womtool

build:
  # Cannot build on Windows because findutils is not available
  skip: true  # [win]
  number: 0

requirements:
  run:
    - openjdk >=11,<12
    - python
    - findutils
    - subprocess32  # [py==27]

test:
  commands:
    - cromwell --version 2>&1 | grep "cromwell"
    - womtool --help 2>&1 | grep "Usage"

about:
  home: https://github.com/broadinstitute/cromwell
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A Workflow Management System geared towards scientific workflows described in WDL
  doc_url: https://cromwell.readthedocs.io/en/stable/
  dev_url: https://github.com/broadinstitute/cromwell

extra:
  recipe-maintainers:
    - notestaff
    - chapmanb
    - micknudsen
    - rhpvorderman
