{% set version = "89" %}

package:
  name: cromwell
  version: {{ version }}

source:
  - url: https://github.com/broadinstitute/cromwell/releases/download/{{ version }}/cromwell-{{ version }}.jar
    sha256: afc761fc05b31a63a1157d112c64db77222aa2397dfd2f6c974dc44db689090d
    folder: cromwell
  - url: https://github.com/broadinstitute/cromwell/releases/download/{{ version }}/womtool-{{ version }}.jar
    sha256: beece815cbc7ddb48c49ef4511e1e794d6d2f3cb933f29265708a5c61c87fb4e
    folder: womtool

build:
  # Cannot build on Windows because findutils is not available
  skip: true  # [win]
  number: 0

requirements:
  run:
    - openjdk >=17,<18
    - python
    - findutils

test:
  commands:
    - cromwell --version 2>&1 | grep "cromwell"
    - womtool --help 2>&1 | grep "Usage"
    - womtool validate tests/test-wdl.wdl
    - cromwell run tests/test-wdl.wdl
  files:
    - "tests"

about:
  home: https://github.com/broadinstitute/cromwell
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A Workflow Management System geared towards scientific workflows described in WDL
  doc_url: https://cromwell.readthedocs.io/en/stable/
  dev_url: https://github.com/broadinstitute/cromwell

extra:
  recipe-maintainers:
    - notestaff
    - chapmanb
    - micknudsen
    - rhpvorderman
