{% set version = "83" %}

package:
  name: cromwell
  version: {{ version }}

source:
  - url: https://github.com/broadinstitute/cromwell/releases/download/{{ version }}/cromwell-{{ version }}.jar
    sha256: bc556fe10cf4798617786fd41533dc06a53941c6ecb849b7b6c6c550220f40c1
    folder: cromwell
  - url: https://github.com/broadinstitute/cromwell/releases/download/{{ version }}/womtool-{{ version }}.jar
    sha256: a1f941da233e06d0a4c261ec3eae91bc62fba5dad200dae0f1e2527672ac58c0
    folder: womtool

build:
  # Cannot build on Windows because findutils is not available
  skip: true  # [win]
  number: 0

requirements:
  run:
    - openjdk >=11,<12
    - python
    - findutils
    - subprocess32  # [py==27]

test:
  commands:
    - cromwell --version 2>&1 | grep "cromwell"
    - womtool --help 2>&1 | grep "Usage"

about:
  home: https://github.com/broadinstitute/cromwell
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A Workflow Management System geared towards scientific workflows described in WDL
  doc_url: https://cromwell.readthedocs.io/en/stable/
  dev_url: https://github.com/broadinstitute/cromwell

extra:
  recipe-maintainers:
    - notestaff
    - chapmanb
    - micknudsen
    - rhpvorderman
