{% set version = "75" %}

package:
  name: cromwell
  version: {{ version }}

source:
  - url: https://github.com/broadinstitute/cromwell/releases/download/{{ version }}/cromwell-{{ version }}.jar
    sha256: 9c66e068a69a922678032a89e27ce4401493957018fa2aa4d82d5e1af3abf5c8
    folder: cromwell
  - url: https://github.com/broadinstitute/cromwell/releases/download/{{ version }}/womtool-{{ version }}.jar
    sha256: 16b64d1c1566dfe53006e2bccce3a9fcb3f98312195172d8d00e84382812ec13
    folder: womtool

build:
  # Cannot build on Windows because findutils is not available
  skip: true  # [win]
  number: 0

requirements:
  run:
    - openjdk >=11,<12
    - python
    - findutils
    - subprocess32  # [py==27]

test:
  commands:
    - cromwell --version 2>&1 | grep "cromwell"
    - womtool --help 2>&1 | grep "Usage"

about:
  home: https://github.com/broadinstitute/cromwell
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A Workflow Management System geared towards scientific workflows described in WDL
  doc_url: https://cromwell.readthedocs.io/en/stable/
  dev_url: https://github.com/broadinstitute/cromwell

extra:
  recipe-maintainers:
    - notestaff
    - chapmanb
    - micknudsen
    - rhpvorderman
